/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package parqueadero.gui;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author korez
 */
public class VentanaEstado extends javax.swing.JFrame {
    private VentanaRegistro ventanaRegistro;
    private VentanaPrincipal ventanaPrincipal;
    
    public void setVentanaPrincipal(VentanaPrincipal ventanaPrincipal){
        this.ventanaPrincipal = ventanaPrincipal;
    }
    
    
    /**
     * Esta funcion es la del mapa del parqueadero
     */
    public void mapaParqueadero(){
        jTarifa.setText(String.valueOf(ventanaPrincipal.getGestor().getTarifa()));
        jPorcentajes.setText(ventanaPrincipal.getGestor().porcentajeParqueadero());
        
        int filas = ventanaPrincipal.getGestor().getFilas();
        int columnas = ventanaPrincipal.getGestor().getColumnas();
        
        jMapa.removeAll();   //al ingresar nuevas columnas y filas se reinicia el mapa
        
        String [][] estado = ventanaPrincipal.getGestor().estadoParqueadero();
        for (int f = 0; f < filas; f++) {
            for (int c = 0; c < columnas; c++) {
                JPanel lugar = new JPanel();   //lugares de parqueo
                JLabel texto = new JLabel();
                texto.setText(String.valueOf(f)+","+String.valueOf(c));
                lugar.add(texto);  
                lugar.setPreferredSize(new Dimension((jMapa.getHeight()/columnas) - 6, (jMapa.getWidth()/filas) - 6)); //dimensiones del mapa para crear los cuadros (lugares de parqueo)
                if (estado[f][c].equals("Libre")){
                    lugar.setBackground(Color.LIGHT_GRAY);  
                }else{
                    lugar.setBackground(Color.red);
                }
                jMapa.add(lugar);
            }
        }
    }
    /**
     * Creates new form VentanaEstado
     */
    public VentanaEstado() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPorcentajes = new javax.swing.JLabel();
        bParquear = new javax.swing.JButton();
        bDesaparcar = new javax.swing.JButton();
        bValor = new javax.swing.JButton();
        bRegistrar = new javax.swing.JButton();
        jTarifa = new javax.swing.JLabel();
        jMapa = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bVolver.setBackground(new java.awt.Color(36, 107, 142));
        bVolver.setForeground(new java.awt.Color(255, 255, 255));
        bVolver.setText("Volver");
        bVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVolverActionPerformed(evt);
            }
        });
        getContentPane().add(bVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Libres / Ocupados");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jPorcentajes.setForeground(new java.awt.Color(255, 255, 255));
        jPorcentajes.setText("text");
        getContentPane().add(jPorcentajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        bParquear.setBackground(new java.awt.Color(36, 107, 142));
        bParquear.setForeground(new java.awt.Color(255, 255, 255));
        bParquear.setText("Parquear");
        bParquear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bParquearActionPerformed(evt);
            }
        });
        getContentPane().add(bParquear, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 100, -1));

        bDesaparcar.setBackground(new java.awt.Color(36, 107, 142));
        bDesaparcar.setForeground(new java.awt.Color(255, 255, 255));
        bDesaparcar.setText("Desaparcar");
        bDesaparcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDesaparcarActionPerformed(evt);
            }
        });
        getContentPane().add(bDesaparcar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 100, -1));

        bValor.setBackground(new java.awt.Color(36, 107, 142));
        bValor.setForeground(new java.awt.Color(255, 255, 255));
        bValor.setText("Valor Total");
        bValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bValorActionPerformed(evt);
            }
        });
        getContentPane().add(bValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 100, -1));

        bRegistrar.setBackground(new java.awt.Color(36, 107, 142));
        bRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        bRegistrar.setText("Registrar");
        bRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(bRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 100, -1));

        jTarifa.setForeground(new java.awt.Color(255, 255, 255));
        jTarifa.setText("text");
        getContentPane().add(jTarifa, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, -1, -1));
        getContentPane().add(jMapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 260, 260));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("La tarifa está: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parqueadero/imagenes/bordeBlanco.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 240, 10));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parqueadero/imagenes/bordeBlanco.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 240, 10));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parqueadero/imagenes/logoPequeño.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 80, 80));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parqueadero/imagenes/bordeBlanco.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 240, 10));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parqueadero/imagenes/borde_1.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 240, 360));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parqueadero/imagenes/fondoredireccionado.jpg"))); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(700, 500));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 630, 360));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parqueadero/imagenes/borde_1.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 240, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVolverActionPerformed
        ventanaPrincipal.setVisible(true);
        if (ventanaRegistro != null){
            ventanaRegistro.setVisible(false);
        }
        this.dispose();
    }//GEN-LAST:event_bVolverActionPerformed

    private void bParquearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bParquearActionPerformed
        String placa = JOptionPane.showInputDialog("Ingresar placa: ");
        String documento = JOptionPane.showInputDialog("Ingresar documento: ");
        JOptionPane.showMessageDialog(this, ventanaPrincipal.getGestor().parquearVehiculo(documento,placa), "INFORMACION: ", JOptionPane.INFORMATION_MESSAGE);
        mapaParqueadero();
    }//GEN-LAST:event_bParquearActionPerformed

    private void bDesaparcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDesaparcarActionPerformed
        String placa = JOptionPane.showInputDialog("Ingresar placa: ");
        String documento = JOptionPane.showInputDialog("Ingresar documento: ");
        JOptionPane.showMessageDialog(this, ventanaPrincipal.getGestor().desaparcarVehiculo(documento,placa), "INFORMACION: ", JOptionPane.INFORMATION_MESSAGE);
        mapaParqueadero();
    }//GEN-LAST:event_bDesaparcarActionPerformed

    private void bValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bValorActionPerformed
        JOptionPane.showMessageDialog(this, ventanaPrincipal.getGestor().valorTotal(), "INFORMACION: ", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_bValorActionPerformed

    private void bRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegistrarActionPerformed
        if (ventanaRegistro == null){
            ventanaRegistro = new VentanaRegistro();
            ventanaRegistro.setVentanaEstado(this);
            ventanaRegistro.setVentanaPrincipal(ventanaPrincipal);
        }
        ventanaRegistro.setVisible(true);
    }//GEN-LAST:event_bRegistrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bDesaparcar;
    private javax.swing.JButton bParquear;
    private javax.swing.JButton bRegistrar;
    private javax.swing.JButton bValor;
    private javax.swing.JButton bVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jMapa;
    private javax.swing.JLabel jPorcentajes;
    private javax.swing.JLabel jTarifa;
    // End of variables declaration//GEN-END:variables
}
