/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package parqueadero.gui;

import javax.swing.JOptionPane;
import parqueadero.java.GestorParqueadero;

/**
 *
 * @author korez
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    private GestorParqueadero gestor;
    private VentanaContrasena ventanaContrasena;
    private VentanaEstado ventanaEstado;
    
    public GestorParqueadero getGestor() {
        return gestor;
    }
    public void setGestor(GestorParqueadero gestor) {
        this.gestor = gestor;
    }
    
    public void setVentanaContrasena(VentanaContrasena ventanaContrasena){
        this.ventanaContrasena = ventanaContrasena;
    }
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bAjustes = new javax.swing.JButton();
        bEstado = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bAjustes.setBackground(new java.awt.Color(23, 64, 84));
        bAjustes.setForeground(new java.awt.Color(255, 255, 255));
        bAjustes.setText("Ajustes");
        bAjustes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAjustesActionPerformed(evt);
            }
        });
        getContentPane().add(bAjustes, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        bEstado.setBackground(new java.awt.Color(23, 64, 84));
        bEstado.setForeground(new java.awt.Color(255, 255, 255));
        bEstado.setText("Parqueadero");
        bEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEstadoActionPerformed(evt);
            }
        });
        getContentPane().add(bEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, -1));

        bSalir.setBackground(new java.awt.Color(23, 64, 84));
        bSalir.setForeground(new java.awt.Color(255, 255, 255));
        bSalir.setText("Salir");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });
        getContentPane().add(bSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parqueadero/imagenes/logoparqueadero-removebg-preview (1).png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 330, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parqueadero/imagenes/fondoredireccionado.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAjustesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAjustesActionPerformed
        ventanaContrasena.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bAjustesActionPerformed

    private void bEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEstadoActionPerformed
        if (ventanaEstado == null){
            ventanaEstado = new VentanaEstado();
            ventanaEstado.setVentanaPrincipal(this);
        }
        ventanaEstado.actualizarTexto();
        ventanaEstado.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bEstadoActionPerformed

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bSalirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAjustes;
    private javax.swing.JButton bEstado;
    private javax.swing.JButton bSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
