package parqueadero.gui;

import javax.swing.JOptionPane;
import parqueadero.componentes.Cliente;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author korez
 */
public class VentanaRegistro extends javax.swing.JFrame {
    private VentanaEstado ventanaEstado;
    private VentanaPrincipal ventanaPrincipal;
    /**
     * Creates new form VentanaRegistro
     */
    public void setVentanaEstado(VentanaEstado ventanaEstado){
        this.ventanaEstado = ventanaEstado;
    }
    public void setVentanaPrincipal(VentanaPrincipal ventanaPrincipal){
        this.ventanaPrincipal = ventanaPrincipal;
    }
    public VentanaRegistro() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bCerrar = new javax.swing.JButton();
        tNombre = new javax.swing.JTextField();
        tDocumento = new javax.swing.JTextField();
        tCelular = new javax.swing.JTextField();
        tMarca = new javax.swing.JTextField();
        tColor = new javax.swing.JTextField();
        tPlaca = new javax.swing.JTextField();
        bRegistrar = new javax.swing.JButton();
        bLimpiar = new javax.swing.JButton();
        bBuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bCerrar.setBackground(new java.awt.Color(36, 107, 142));
        bCerrar.setForeground(new java.awt.Color(255, 255, 255));
        bCerrar.setText("Cerrar");
        bCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(bCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, -1));

        tNombre.setBackground(new java.awt.Color(23, 44, 55));
        tNombre.setForeground(new java.awt.Color(255, 255, 255));
        tNombre.setText("Nombre");
        tNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tNombreMousePressed(evt);
            }
        });
        tNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNombreActionPerformed(evt);
            }
        });
        getContentPane().add(tNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 115, -1));

        tDocumento.setBackground(new java.awt.Color(23, 44, 55));
        tDocumento.setForeground(new java.awt.Color(255, 255, 255));
        tDocumento.setText("Documento");
        tDocumento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tDocumentoMousePressed(evt);
            }
        });
        tDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tDocumentoActionPerformed(evt);
            }
        });
        getContentPane().add(tDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 115, -1));

        tCelular.setBackground(new java.awt.Color(23, 44, 55));
        tCelular.setForeground(new java.awt.Color(255, 255, 255));
        tCelular.setText("Celular");
        tCelular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tCelularMousePressed(evt);
            }
        });
        tCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tCelularActionPerformed(evt);
            }
        });
        getContentPane().add(tCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 115, -1));

        tMarca.setBackground(new java.awt.Color(23, 44, 55));
        tMarca.setForeground(new java.awt.Color(255, 255, 255));
        tMarca.setText("Marca");
        tMarca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tMarcaMousePressed(evt);
            }
        });
        tMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tMarcaActionPerformed(evt);
            }
        });
        getContentPane().add(tMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 115, -1));

        tColor.setBackground(new java.awt.Color(23, 44, 55));
        tColor.setForeground(new java.awt.Color(255, 255, 255));
        tColor.setText("Color");
        tColor.setPreferredSize(new java.awt.Dimension(64, 22));
        tColor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tColorMousePressed(evt);
            }
        });
        tColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tColorActionPerformed(evt);
            }
        });
        getContentPane().add(tColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 115, -1));

        tPlaca.setBackground(new java.awt.Color(23, 44, 55));
        tPlaca.setForeground(new java.awt.Color(255, 255, 255));
        tPlaca.setText("Placa");
        tPlaca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tPlacaMousePressed(evt);
            }
        });
        tPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPlacaActionPerformed(evt);
            }
        });
        getContentPane().add(tPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 115, -1));

        bRegistrar.setBackground(new java.awt.Color(23, 44, 55));
        bRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        bRegistrar.setText("Registrar");
        bRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(bRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, -1, -1));

        bLimpiar.setBackground(new java.awt.Color(23, 44, 55));
        bLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        bLimpiar.setText("Limpiar");
        bLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(bLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, -1, -1));

        bBuscar.setBackground(new java.awt.Color(23, 44, 55));
        bBuscar.setForeground(new java.awt.Color(255, 255, 255));
        bBuscar.setText("Buscar");
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(bBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Park Central");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parqueadero/imagenes/logoparqueadero-removebg-preview (1).png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 40, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parqueadero/imagenes/borde.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 110));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parqueadero/imagenes/fondoredireccionado.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_bCerrarActionPerformed

    private void tCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tCelularActionPerformed

    private void tNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNombreActionPerformed

    private void tDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tDocumentoActionPerformed

    private void tMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tMarcaActionPerformed

    private void tPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tPlacaActionPerformed

    private void bRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegistrarActionPerformed
        String nombre = tNombre.getText();
        String documento = tDocumento.getText();
        String celular = tCelular.getText();
        
        String color = tColor.getText();
        String marca = tMarca.getText();
        String placa = tPlaca.getText();
        
        if(tNombre.getText().isEmpty() || tCelular.getText().isEmpty() || tDocumento.getText().isEmpty() || tColor.getText().isEmpty() || tMarca.getText().isEmpty() || tPlaca.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Hay campos sin rellenar", "Error", JOptionPane.WARNING_MESSAGE);
        }else{
            String message = ventanaPrincipal.getGestor().registrarCliente(nombre, documento, celular, color, marca, placa);
            JOptionPane.showMessageDialog(this, message, "Estado", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_bRegistrarActionPerformed

    private void bLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimpiarActionPerformed
        tNombre.setText("");
        tDocumento.setText("");
        tCelular.setText("");
        
        tColor.setText("");
        tMarca.setText("");
        tPlaca.setText("");
    }//GEN-LAST:event_bLimpiarActionPerformed

    private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarActionPerformed
        String documento = JOptionPane.showInputDialog("Ingresar documento: ");
        
        Cliente cliente = ventanaPrincipal.getGestor().buscarCliente(documento);
        if(cliente == null){
            JOptionPane.showMessageDialog(this, "No se encontro el cliente", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            tNombre.setText(cliente.getNombre());
            tDocumento.setText(cliente.getDocumento());
            tCelular.setText(cliente.getCelular());
            tColor.setText(cliente.getVehiculo().getColor());
            tMarca.setText(cliente.getVehiculo().getMarca());
            tPlaca.setText(cliente.getVehiculo().getPlaca());
        }
    }//GEN-LAST:event_bBuscarActionPerformed

    private void tMarcaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tMarcaMousePressed
        if(tMarca.getText().equals("Marca")){
            tMarca.setText("");
        }
        if(tPlaca.getText().isEmpty()){
            tPlaca.setText("Placa");
        }
        
        if(tColor.getText().isEmpty()){
            tColor.setText("Color");
        }
                if(tNombre.getText().isEmpty()){
            tNombre.setText("Nombre");
        }
        
        if(tDocumento.getText().isEmpty()){
            tDocumento.setText("Documento");
        }
        
        if(tCelular.getText().isEmpty()){
            tCelular.setText("Celular");
        }
    }//GEN-LAST:event_tMarcaMousePressed

    private void tPlacaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tPlacaMousePressed
        if(tPlaca.getText().equals("Placa")){
            tPlaca.setText("");
        }
       
        if(tMarca.getText().isEmpty()){
            tMarca.setText("Marca");
        }    
        if(tColor.getText().isEmpty()){
            tColor.setText("Color");
        }
        if(tNombre.getText().isEmpty()){
            tNombre.setText("Nombre");
        }
        
        if(tDocumento.getText().isEmpty()){
            tDocumento.setText("Documento");
        }
        
        if(tCelular.getText().isEmpty()){
            tCelular.setText("Celular");
        }
    }//GEN-LAST:event_tPlacaMousePressed

    private void tNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tNombreMousePressed
        if(tNombre.getText().equals("Nombre")){
            tNombre.setText("");
        }        
        if(tPlaca.getText().isEmpty()){
            tPlaca.setText("Placa");
        }
        
        if(tColor.getText().isEmpty()){
            tColor.setText("Color");
        }
        if(tMarca.getText().isEmpty()){
            tMarca.setText("Marca");
        }
        
        if(tDocumento.getText().isEmpty()){
            tDocumento.setText("Documento");
        }
        
        if(tCelular.getText().isEmpty()){
            tCelular.setText("Celular");
        }
    }//GEN-LAST:event_tNombreMousePressed

    private void tDocumentoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tDocumentoMousePressed
        if(tDocumento.getText().equals("Documento")){
            tDocumento.setText("");
        }        
        if(tPlaca.getText().isEmpty()){
            tPlaca.setText("Placa");
        }
        
        if(tColor.getText().isEmpty()){
            tColor.setText("Color");
        }
        if(tMarca.getText().isEmpty()){
            tMarca.setText("Marca");
        }
        
        if(tNombre.getText().isEmpty()){
            tNombre.setText("Nombre");
        }
        
        if(tCelular.getText().isEmpty()){
            tCelular.setText("Celular");
        }
    }//GEN-LAST:event_tDocumentoMousePressed

    private void tCelularMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tCelularMousePressed
     if(tCelular.getText().equals("Celular")){
        tCelular.setText("");
        }      
    
     if(tPlaca.getText().isEmpty()){
            tPlaca.setText("Placa");
        }
        
        if(tColor.getText().isEmpty()){
            tColor.setText("Color");
        }
        if(tMarca.getText().isEmpty()){
            tMarca.setText("Marca");
        }
        
        if(tNombre.getText().isEmpty()){
            tNombre.setText("Nombre");
        }
        
        if(tDocumento.getText().isEmpty()){
            tDocumento.setText("Documento");
        }
     
    }//GEN-LAST:event_tCelularMousePressed

    private void tColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tColorActionPerformed

    private void tColorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tColorMousePressed
        if(tColor.getText().equals("Color")){
            tColor.setText("");
        }
        if(tPlaca.getText().isEmpty()){
            tPlaca.setText("Placa");
        }
        
        if(tMarca.getText().isEmpty()){
            tMarca.setText("Marca");
        }
        
        if(tNombre.getText().isEmpty()){
            tNombre.setText("Nombre");
        }
        
        if(tDocumento.getText().isEmpty()){
            tDocumento.setText("Documento");
        }
        
        if(tCelular.getText().isEmpty()){
            tCelular.setText("Celular");
        }
    }//GEN-LAST:event_tColorMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBuscar;
    private javax.swing.JButton bCerrar;
    private javax.swing.JButton bLimpiar;
    private javax.swing.JButton bRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField tCelular;
    private javax.swing.JTextField tColor;
    private javax.swing.JTextField tDocumento;
    private javax.swing.JTextField tMarca;
    private javax.swing.JTextField tNombre;
    private javax.swing.JTextField tPlaca;
    // End of variables declaration//GEN-END:variables
}
