/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package parqueadero.gui;
import javax.swing.JOptionPane;
import parqueadero.java.GestorParqueadero;

/**
 *
 * @author korez
 */
public class VentanaContrasena extends javax.swing.JFrame {
    private VentanaPrincipal ventanaPrincipal;
    private VentanaModificador ventanaModificador;
    /**
     * Creates new form VentanaContrasena
     */
    public VentanaContrasena() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tContrasena = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        bIngresar = new javax.swing.JButton();
        bVolver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLogo = new javax.swing.JLabel();
        bSalir = new javax.swing.JButton();
        jFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tContrasena.setBackground(new java.awt.Color(23, 44, 55));
        tContrasena.setForeground(new java.awt.Color(255, 255, 255));
        tContrasena.setText("Contraseña");
        tContrasena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tContrasenaMousePressed(evt);
            }
        });
        tContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tContrasenaActionPerformed(evt);
            }
        });
        getContentPane().add(tContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 263, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Contraseña");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        bIngresar.setBackground(new java.awt.Color(23, 64, 84));
        bIngresar.setForeground(new java.awt.Color(255, 255, 255));
        bIngresar.setText("Ingresar");
        bIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(bIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, -1));

        bVolver.setBackground(new java.awt.Color(23, 64, 84));
        bVolver.setForeground(new java.awt.Color(255, 255, 255));
        bVolver.setText("Volver");
        bVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVolverActionPerformed(evt);
            }
        });
        getContentPane().add(bVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Park Central");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 150, 40));

        jLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parqueadero/imagenes/logoparqueadero-removebg-preview (1).png"))); // NOI18N
        getContentPane().add(jLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 220, 160));

        bSalir.setBackground(new java.awt.Color(23, 64, 84));
        bSalir.setForeground(new java.awt.Color(255, 255, 255));
        bSalir.setText("Salir");
        bSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSalirMouseClicked(evt);
            }
        });
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });
        getContentPane().add(bSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parqueadero/imagenes/fondoredireccionado.jpg"))); // NOI18N
        getContentPane().add(jFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 397, 304));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tContrasenaActionPerformed

    }//GEN-LAST:event_tContrasenaActionPerformed

    private void bIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIngresarActionPerformed
        String contrasena = tContrasena.getText();
        if (ventanaPrincipal != null){
            if(ventanaPrincipal.getGestor().ingresoContrasena(contrasena)){
                ventanaModificador.setVisible(true);
                tContrasena.setText("");
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(this, "La contraseña no es correcta \n        Vuelva a intentar", "¡Incorrecto!", JOptionPane.WARNING_MESSAGE);
            }
        }else{
            this.ventanaPrincipal = new VentanaPrincipal();
            this.ventanaModificador = new VentanaModificador();
            GestorParqueadero gestor = new GestorParqueadero(contrasena);
            ventanaPrincipal.setGestor(gestor);
            ventanaPrincipal.setVentanaContrasena(this);
            ventanaModificador.setVentanaPrincipal(ventanaPrincipal);
            ventanaModificador.setVisible(true);
            tContrasena.setText("");
            this.dispose();
        }
    }//GEN-LAST:event_bIngresarActionPerformed

    private void bVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVolverActionPerformed
        if (ventanaPrincipal != null){
            ventanaPrincipal.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(this, "¡No hay ningun parqueadero registrado! \n        Ingrese nueva contraseña", "¡Espera!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_bVolverActionPerformed

    private void tContrasenaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tContrasenaMousePressed
        // TODO add your handling code here:
         if(tContrasena.getText().equals("Contraseña")){
            tContrasena.setText("");
        }
    }//GEN-LAST:event_tContrasenaMousePressed

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_bSalirActionPerformed

    private void bSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSalirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bSalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       VentanaContrasena ventanaContrasena = new VentanaContrasena();
       ventanaContrasena.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bIngresar;
    private javax.swing.JButton bSalir;
    private javax.swing.JButton bVolver;
    private javax.swing.JLabel jFondo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLogo;
    private javax.swing.JTextField tContrasena;
    // End of variables declaration//GEN-END:variables
}
